language: node_js
node_js:
- 8
before_install:
- sudo apt-get -qq update
install:
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
- npm install
before_script:
- openssl aes-256-cbc -K $deploy_key_pass -iv $deploy_key_iv -in config/firebase-adminsdk.json.enc -out config/firebase-adminsdk.json -d
- openssl aes-256-cbc -K $deploy_key_pass -iv $deploy_key_iv -in config/google-storageadmin.json.enc -out config/google-storageadmin.json -d
script:
- cd cron
- node backup.js
- node allbooklets.js -t30
notifications:
  email: false
  slack: the-tricktionary:VdZSlFi4J1AHCcQY96RU5dDZ
